// Regenerates public/sitemap.xml from the product catalog so it can't drift
// out of sync with the router again. Run: npm run sitemap
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ORIGIN = 'https://axonring.com';

const catalog = readFileSync(resolve(root, 'src/data/catalog.ts'), 'utf8');

// The catalog is static data; pull handles straight out of it rather than
// standing up a TS build just for this script. Products and collections both
// use `handle:` at the same indent, so split them on the COLLECTIONS boundary.
const collectionsStart = catalog.indexOf('export const COLLECTIONS');
const productsPart = catalog.slice(0, collectionsStart);
const collectionsPart = catalog.slice(collectionsStart);
const products = [...productsPart.matchAll(/^\s{4}handle: '([^']+)',$/gm)].map(m => m[1]);
const collections = [...collectionsPart.matchAll(/^\s{4}handle: '([^']+)',$/gm)].map(m => m[1]);

if (products.length === 0 || collections.length === 0) {
  throw new Error(`Parsed 0 products (${products.length}) or 0 collections (${collections.length}) — catalog format changed?`);
}

const STATIC_PAGES = [
  { path: '/', priority: '1.0', changefreq: 'weekly' },
  { path: '/size-guide', priority: '0.8', changefreq: 'monthly' },
  { path: '/faq', priority: '0.7', changefreq: 'monthly' },
  { path: '/shipping', priority: '0.5', changefreq: 'monthly' },
  { path: '/returns', priority: '0.5', changefreq: 'monthly' },
  { path: '/privacy', priority: '0.3', changefreq: 'yearly' },
  { path: '/terms', priority: '0.3', changefreq: 'yearly' },
];

const today = new Date().toISOString().slice(0, 10);

const urls = [
  ...STATIC_PAGES.map(p => ({ loc: `${ORIGIN}${p.path}`, priority: p.priority, changefreq: p.changefreq })),
  ...collections.map(h => ({ loc: `${ORIGIN}/collections/${h}`, priority: '0.9', changefreq: 'weekly' })),
  ...products.map(h => ({ loc: `${ORIGIN}/product/${h}`, priority: '0.8', changefreq: 'weekly' })),
];

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    u => `  <url>
    <loc>${u.loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`
  )
  .join('\n')}
</urlset>
`;

writeFileSync(resolve(root, 'public/sitemap.xml'), xml);
console.log(`sitemap.xml: ${urls.length} URLs (${products.length} products, ${collections.length} collections, ${STATIC_PAGES.length} static)`);
